apiVersion: v1
kind: Pod
metadata:
  name: {{ include "laa-dces-drc-integration-int-tests.fullname" . }}
  labels:
    {{- include "laa-dces-drc-integration-int-tests.labels" . | nindent 4 }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  containers:
    - name: {{ .Chart.Name }}
      stdin: True
      tty: True
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{ include "laa-dces-drc-integration-int-test.env-vars" . | nindent 6 }}
      envFrom:
        - secretRef:
            name: dces-datasource
            optional: false
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
  restartPolicy: Never
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
