# This should be kept in lockstep with the main application.yaml

server:
  port: 8089

management:
  server:
    port: 8188
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

sentry:
  debug: off
  dsn: https://73c8b29cf60925dfb51ff991af098c8f@o345774.ingest.sentry.io/4506031610462208
  # With a sample rate of 1, all traffic will be sent to Sentry. Note, this is only possible because this project will have very low traffic (2 calls  month)
  traces-sample-rate: 1.0
  environment: ${HOST_ENV}
  release: 1.0.0
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  # With a sample rate of 1, all traffic will be sent to Sentry. Note, this is only possible because this project will have very low traffic (2 calls  month)
  sample-rate: 1.00
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: info
  in-app-includes: uk.gov.justice.laa.crime.dces.integration

logging:
  config: "classpath:logback-json.xml"
  level:
    level: debug
    uk.gov.justice.laa.crime.dces.integration: debug
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.http: debug
    org.springframework.security.oauth2: debug
    org.springframework.security.oauth2.client: debug

services:
  maat-api:
    baseUrl: ${MAAT_API_BASE_URL}
    registrationId: ${MAAT_API_REGISTRATION_ID}
    oAuthEnabled: true
    maxBufferSize: 16
  drc-client-api:
    baseUrl: http://localhost:1110
    oAuthEnabled: false

spring:
  security:
    oauth2:
      client:
        provider:
          maatapi:
            token-uri: ${MAAT_API_OAUTH_URL}
            token-base-uri: ${MAAT_API_OAUTH_BASE_URL}
        registration:
          maatapi:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - ${MAAT_API_OAUTH_SCOPE}
      resource-server:
        jwt:
          issuer-uri: ${LAA_DCES_DRC_INTEGRATION_RESOURCE_SERVER_ISSUER_URI}

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    operations-sorter: method
  api-docs:
    path: "/api-docs"
    enabled: true
  writer-with-order-by-keys: true
  writer-with-default-pretty-printer: true
  packages-to-scan: uk.gov.justice.laa.crime.dces.integration.rest.api.controller

api:
  title: DCES DRC Integration RestAPIs
  description: DCES DRC Integration Services.
  version: 1.0
  contactName: DCES Support Team
  contactEmail: laa-dces@digital.justice.gov.uk
  contactUrl: justice.gov.uk/laa
