server:
  port: 8089

management:
  server:
    port: 8188
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

sentry:
  debug: off
  dsn: https://73c8b29cf60925dfb51ff991af098c8f@o345774.ingest.sentry.io/4506031610462208
  # With a sample rate of 1, all traffic will be sent to Sentry. Note, this is only possible because this project will have very low traffic (2 calls  month)
  traces-sample-rate: 1.0
  environment: ${HOST_ENV}
  release: 1.0.0
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  # With a sample rate of 1, all traffic will be sent to Sentry. Note, this is only possible because this project will have very low traffic (2 calls  month)
  sample-rate: 1.00
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: info
  in-app-includes: uk.gov.justice.laa.crime.dces.integration

services:
  maat-api:
    baseUrl: ${MAAT_API_BASE_URL}
    registrationId: ${MAAT_API_REGISTRATION_ID}
    oAuthEnabled: true
    maxBufferSize: 16

spring:
  security:
    oauth2:
      client:
        provider:
          maatapi:
            token-uri: ${MAAT_API_OAUTH_URL}
        registration:
          maatapi:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - ${MAAT_API_OAUTH_SCOPE}
      resource-server:
        jwt:
          issuer-uri: ${LAA_DCES_DRC_INTEGRATION_RESOURCE_SERVER_ISSUER_URI}