{{- if .Values.privateIngress.enabled -}}
{{- $fullName := include "laa-dces-drc-integration.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "laa-dces-drc-integration.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.privateIngress.annotations.nonMtls }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.privateIngress.annotations.common }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- include "laa-dces-drc-integration.allowlistMon" . | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls.hosts }}
    - hosts:
        {{- range .host }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  rules:
    {{- range .Values.ingress.mon.hosts }}
      - host: {{ . }}
        http:
          paths:
          {{- range $.Values.ingress.mon.paths }}
            - backend:
                service:
                  name: {{ $fullName }}
                  port:
                    number: {{ .port}}
              path: {{ .path }}
              pathType: {{ .pathType}}
          {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
