{{- if .Values.ingress.enabled -}}
{{- $fullName := include "laa-dces-drc-integration.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "laa-dces-drc-integration.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.ingress.annotations.nonMtls }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.annotations.common }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .host }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.mon.host | quote }}
      http:
        paths:
{{/*          - path: {{ $.Values.actuator.metrics.path }}*/}}
{{/*            pathType: "Exact"*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ $fullName }}*/}}
{{/*                port:*/}}
{{/*                  number: {{ $.Values.actuator.port }}*/}}
{{/*          - path: {{ $.Values.actuator.health.path }}*/}}
{{/*            pathType: "Exact"*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ $fullName }}*/}}
{{/*                port:*/}}
{{/*                  number: {{ $.Values.actuator.port }}*/}}
{{/*          - path: "/api-docs"*/}}
{{/*            pathType: "Exact"*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ $fullName }}*/}}
{{/*                port:*/}}
{{/*                  number: {{ $svcPort }}*/}}
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{/*          - path: "/swagger-ui-custom.html"*/}}
{{/*            pathType: "Exact"*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ $fullName }}*/}}
{{/*                port:*/}}
{{/*                  number: {{ $svcPort }}*/}}
{{/*          - path: "/error"*/}}
{{/*            pathType: "Exact"*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ $fullName }}*/}}
{{/*                port:*/}}
{{/*                  number: {{ $svcPort }}*/}}

  {{- end }}
