apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-dces-drc-integration.fullname" . }}
  labels:
    {{- include "laa-dces-drc-integration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    {{- if not (eq (toString .Values.actuator.port) "http") }}
    - port: {{ .Values.actuator.port }}
      targetPort: actuator
      protocol: TCP
      name: actuator
    {{- end }}
  selector:
    {{- include "laa-dces-drc-integration.selectorLabels" . | nindent 4 }}
