name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk:
    name: Run Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Your Java version
          distribution: 'temurin'

      - name: Install Snyk CLI
        uses: snyk/actions/setup@v2
        with:
          version: 'latest'

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Test with Snyk
        run: snyk test --all-projects --severity-threshold=medium

      - name: Monitor with Snyk
        run: snyk monitor